import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Result'
import requests from '../utils/requests'
import {useEffect,useContext} from "react"
import { userAgent } from 'next/server'
import { UserContext } from '../context/UserContext'
import Router from 'next/router'

const Home: NextPage = ({results}:any) => {
  const {user,setUser} = useContext(UserContext)
  //console.log(results)
  useEffect(()=>{
    if (user.username){
      Router.push("/login")
    }
    console.log("user from index page: ",user)
  },[])

  return (
    <div >
      <Head>
        <title>Free Streaming Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header></Header>
        <Navbar></Navbar>
        <Results results={results}></Results>




    </div>
  )
}

export default Home;

export async function getServerSideProps(context:any){
  const genre:any = context.query.genre;
  //console.log(context)
  //console.log(genre)
  //console.log('Context query = ',context.query)
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
    )
    const data = await request.json()

  return{
    props:{
      results:data.results,
    }
  }
}